spring:
  profiles:
    active: dev

grpc:
  client:
    GLOBAL:
      enableKeepAlive: true
    session-grpc:
      address: static://127.0.0.1:10021

config:
  topic:
    word-limit: 20
    notes-limit: 200
  comment:
    word-limit: 300
  manage:
    proposal-word-limit: 500