server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: NON_NULL


grpc:
  client:
    GLOBAL:
      enableKeepAlive: true
    session:
      address: http://localhost:10021